Enforce uniform code formating for all commits.
This is to improve readability of the code from contributors

diff --git a/.github/workflows/L2-tests.yml b/.github/workflows/L2-tests.yml
--- a/.github/workflows/L2-tests.yml
+++ b/.github/workflows/L2-tests.yml
@@ -34,6 +34,26 @@ jobs:
           repository: 'rdkcentral/WebconfigFramework'
           path : 'telemetry/containers/native-platform/WebconfigFramework'
 
+      - name: Install Docker Clang Formatter
+        run: |
+            sudo apt-get update
+            sudo apt-get install clang-format -y
+
+      - name: Check for clang-formatting errors
+        run: |
+          cd telemetry
+          find . -name '*.c' -o -name '*.h' | xargs clang-format -i
+          git diff --name-only --exit-code
+          if [ $? -ne 0 ]; then
+            echo " !!! WARNING !!! "
+            echo "clang-formatting errors found. Please run below code to clang-format in your local workspace and commit"
+            echo "find . -name '*.c' -o -name '*.h' | xargs clang-format -i"
+            exit 1
+          else
+            echo "No clang-formatting errors found."
+          fi
+          cd - 
+ 
       - name: Build Docker image for Mock XCONF Server
         uses: docker/build-push-action@v4
         with:
